// Generated by `npx tsx scripts/generate-study.mts build-catalog` from
// src/content/study/links.ts and tools/ascendra-catalog. Do not edit by hand.

/** OpsForge mission id -> Study objective ids that completing it credits. */
export const MISSION_LINKS: Record<string, string[]> = {
  "bigo-01-growth": [
    "dea-c01:1:27",
    "mscs:1:4",
    "mscs:1:5"
  ],
  "bigo-02-search-sort": [
    "cmpcbs:24:5",
    "mscs:4:3"
  ],
  "bigo-03-structures": [
    "cmpcbs:25:4",
    "dva-c02:1:25",
    "mscs:2:2",
    "mscs:2:3"
  ],
  "design-01-position-ingest": [
    "saa-c03:2:17",
    "secplus:3:7"
  ],
  "design-02-command-ack": [
    "dva-c02:1:24",
    "mscs:9:10"
  ],
  "devops-01-broken-pipeline": [
    "dva-c02:3:22",
    "linuxplus:5:4"
  ],
  "devops-02-green-locally-red-in-ci": [
    "dop-c02:1:9"
  ],
  "devops-03-bad-release-rollback": [
    "cysaplus:3:3",
    "dva-c02:3:24",
    "secplus:4:6"
  ],
  "devops-04-secret-wiring": [
    "dva-c02:2:18",
    "securityx:3:2"
  ],
  "go-02-worker-pool": [
    "dva-c02:1:4",
    "mscs:8:12",
    "mscs:8:17"
  ],
  "go-04-retries-idempotency": [
    "dva-c02:1:12"
  ],
  "go-05-data-race": [
    "dva-c02:4:16",
    "mscs:8:13",
    "mscs:8:14"
  ],
  "incident-01-cache-stampede": [
    "saa-c03:2:11"
  ],
  "incident-02-traffic-surge": [
    "saa-c03:2:7"
  ],
  "incident-03-dead-consumers": [
    "saa-c03:2:4"
  ],
  "incident-04-replica-lag": [
    "mscs:9:9",
    "saa-c03:2:12"
  ],
  "linux-02-log-detective": [
    "dva-c02:4:3",
    "linuxplus:3:6",
    "linuxplus:5:3"
  ],
  "linux-03-locked-out": [
    "linuxplus:1:5",
    "linuxplus:2:2"
  ],
  "linux-04-disk-full": [
    "linuxplus:3:3"
  ],
  "linux-05-runaway-process": [
    "linuxplus:3:5",
    "linuxplus:5:2"
  ],
  "netsec-01-brute-force": [
    "cysaplus:1:7",
    "scs-c03:2:6",
    "secplus:1:6"
  ],
  "netsec-02-suspicious-cron": [
    "cmpcbs:26:5",
    "cysaplus:1:4",
    "cysaplus:3:1",
    "linuxplus:4:5",
    "pentestplus:5:3",
    "scs-c03:2:8",
    "secplus:2:7"
  ],
  "python-01-uptime-report": [
    "python:1:1",
    "python:1:3"
  ],
  "python-02-log-parser": [
    "dop-c02:4:5",
    "python:1:5",
    "python:3:3",
    "python:4:1"
  ],
  "python-03-config-validator": [
    "dva-c02:1:7",
    "python:4:4",
    "python:4:5"
  ],
  "python-04-fleet-report": [
    "dva-c02:1:26",
    "python:4:3"
  ],
  "serverless-01-throttled-function": [
    "saa-c03:2:24"
  ],
  "serverless-02-poison-messages": [
    "dva-c02:1:17"
  ],
  "serverless-03-duplicate-charges": [
    "dop-c02:5:4"
  ],
  "serverless-04-idempotent-handler": [
    "dva-c02:1:8"
  ]
};

/** Planned engine id -> Study unit ids whose gate it would make playable. */
export const ENGINE_GATES: Record<string, string[]> = {
  "dr-planner": [
    "saa-c03:2",
    "soa-c03:2"
  ],
  "net-trace": [
    "ans-c01:3",
    "soa-c03:5"
  ],
  "policy-eval": [
    "scs-c03:4",
    "soa-c03:4"
  ]
};

/** Lab exercise id -> Study objective ids that passing it credits. */
export const LAB_LINKS: Record<string, string[]> = {
  "alarm-01-threshold": [
    "dop-c02:4:16",
    "sap-c02:3:1",
    "soa-c03:1:9"
  ],
  "alarm-02-periods": [
    "ans-c01:4:12",
    "dva-c02:4:2",
    "mla-c02:4:2"
  ],
  "alarm-03-right-metric": [
    "ans-c01:1:23",
    "dop-c02:4:12",
    "soa-c03:1:5"
  ],
  "alarm-04-replica": [
    "dva-c02:4:5",
    "soa-c03:1:17"
  ],
  "alarm-05-function": [
    "soa-c03:1:2"
  ],
  "alarm-06-severity": [
    "dea-c01:3:18",
    "dop-c02:4:22",
    "sap-c02:2:11",
    "soa-c03:1:4"
  ],
  "as-01-elastic": [
    "clf-c02:3:10",
    "mla-c02:4:10",
    "saa-c03:4:11"
  ],
  "as-02-warmup": [
    "dop-c02:3:9",
    "soa-c03:2:1"
  ],
  "as-03-flash-sale": [
    "dop-c02:4:21",
    "sap-c02:2:28"
  ],
  "as-04-thrash": [
    "dop-c02:3:10",
    "sap-c02:2:23"
  ],
  "as-05-health": [
    "ans-c01:1:17",
    "dop-c02:4:26",
    "dva-c02:4:15",
    "scs-c03:1:2",
    "soa-c03:2:4"
  ],
  "as-06-metric": [
    "dop-c02:3:8",
    "mla-c02:3:14",
    "saa-c03:3:7"
  ],
  "cost-01-rightsize": [
    "clf-c02:1:13",
    "saa-c03:4:10",
    "sap-c02:2:32"
  ],
  "cost-02-commit-baseline": [
    "clf-c02:1:10",
    "mla-c02:3:9",
    "saa-c03:4:9",
    "sap-c02:2:33"
  ],
  "cost-03-interruptible": [
    "clf-c02:4:1",
    "dea-c01:1:16",
    "mla-c02:4:12",
    "sap-c02:1:25"
  ],
  "cost-04-tiering": [
    "clf-c02:4:5",
    "saa-c03:4:1",
    "sap-c02:2:34"
  ],
  "cost-05-transfer-path": [
    "clf-c02:4:4",
    "saa-c03:4:18",
    "saa-c03:4:19",
    "soa-c03:5:4"
  ],
  "cost-06-cache-and-alarm": [
    "clf-c02:4:6",
    "clf-c02:4:9",
    "saa-c03:4:21",
    "saa-c03:4:24",
    "sap-c02:3:29",
    "sap-c02:3:31",
    "scs-c03:6:7"
  ],
  "crypto-01-envelope": [
    "clf-c02:2:7",
    "dea-c01:4:15",
    "dva-c02:2:12",
    "sap-c02:1:12"
  ],
  "crypto-02-direct": [
    "dva-c02:2:11",
    "dva-c02:2:17",
    "dva-c02:2:9",
    "sap-c02:2:15",
    "scs-c03:5:4"
  ],
  "crypto-03-unwrap": [
    "soa-c03:4:7"
  ],
  "crypto-04-cross-account": [
    "dea-c01:4:16",
    "dva-c02:2:14",
    "saa-c03:1:17"
  ],
  "crypto-05-rotation": [
    "dop-c02:6:15",
    "dva-c02:2:15",
    "saa-c03:1:19",
    "scs-c03:5:12"
  ],
  "crypto-06-separation": [
    "dop-c02:6:11"
  ],
  "deploy-01-all-at-once": [
    "dop-c02:1:7",
    "sap-c02:3:6"
  ],
  "deploy-02-canary": [
    "dva-c02:3:21",
    "mla-c02:3:20"
  ],
  "deploy-03-latent-defect": [
    "dop-c02:1:23"
  ],
  "deploy-04-blue-green": [
    "dop-c02:1:19",
    "saa-c03:2:23"
  ],
  "deploy-05-too-slow": [
    "soa-c03:3:5"
  ],
  "deploy-06-guard": [
    "dop-c02:5:11",
    "sap-c02:2:4"
  ],
  "dr-01-match-the-need": [
    "clf-c02:3:6",
    "saa-c03:2:20",
    "saa-c03:4:6",
    "sap-c02:2:9"
  ],
  "dr-02-order-api": [
    "dop-c02:3:14",
    "saa-c03:2:19",
    "saa-c03:4:16",
    "sap-c02:1:16",
    "secplus:4:7"
  ],
  "dr-03-payments": [
    "saa-c03:2:21",
    "sap-c02:1:15"
  ],
  "dr-04-untested": [
    "dop-c02:3:15",
    "sap-c02:2:8",
    "soa-c03:2:10"
  ],
  "dr-05-restore-dominates": [
    "sap-c02:1:19",
    "securityx:1:5",
    "soa-c03:2:8"
  ],
  "msg-01-decouple": [
    "clf-c02:3:28",
    "dva-c02:1:3",
    "saa-c03:3:8",
    "sap-c02:4:17"
  ],
  "msg-02-poison": [
    "dea-c01:1:26"
  ],
  "msg-03-redelivery": [
    "sap-c02:2:21"
  ],
  "msg-04-order": [
    "sap-c02:4:20"
  ],
  "msg-05-fanout": [
    "dea-c01:1:10",
    "dop-c02:5:2",
    "dva-c02:1:1",
    "soa-c03:1:8"
  ],
  "msg-06-stream": [
    "dea-c01:1:1",
    "dea-c01:1:9",
    "dva-c02:1:10",
    "mla-c02:1:4",
    "saa-c03:3:21"
  ],
  "net-01-stateful-source": [
    "ans-c01:3:13",
    "dea-c01:4:1",
    "saa-c03:1:8",
    "scs-c03:3:12",
    "soa-c03:5:8"
  ],
  "net-02-stateless-reply": [
    "ans-c01:4:10",
    "clf-c02:3:18",
    "sap-c02:2:13",
    "soa-c03:5:9"
  ],
  "net-03-nat": [
    "clf-c02:3:17",
    "saa-c03:1:9",
    "soa-c03:5:1"
  ],
  "net-04-endpoint": [
    "ans-c01:2:13",
    "mla-c02:4:22",
    "saa-c03:1:16",
    "scs-c03:3:15",
    "soa-c03:5:2"
  ],
  "net-05-hub": [
    "ans-c01:2:14",
    "ans-c01:3:5",
    "saa-c03:3:17"
  ],
  "net-06-rule-order": [
    "ans-c01:2:17",
    "dop-c02:6:9",
    "sap-c02:1:14"
  ],
  "policy-01-default-deny": [
    "clf-c02:2:11",
    "mla-c02:4:19",
    "saa-c03:1:2",
    "sap-c02:2:12"
  ],
  "policy-02-deny-wins": [
    "dea-c01:4:13",
    "scs-c03:4:7",
    "soa-c03:4:2"
  ],
  "policy-03-boundary": [
    "dop-c02:6:5",
    "scs-c03:4:6",
    "scs-c03:4:8"
  ],
  "policy-04-guardrail": [
    "dop-c02:6:4",
    "saa-c03:1:4",
    "scs-c03:6:3",
    "soa-c03:4:3"
  ],
  "policy-05-cross-account": [
    "saa-c03:1:5",
    "scs-c03:4:4"
  ],
  "policy-06-tags": [
    "scs-c03:4:5",
    "soa-c03:4:1"
  ],
  "py-01-truthiness": [
    "python:1:2",
    "python:1:4"
  ],
  "py-02-arguments": [
    "python:2:1"
  ],
  "py-03-closures": [
    "python:2:3",
    "python:7:5"
  ],
  "py-04-recursion": [
    "cmpcbs:24:3",
    "cmpcbs:25:6",
    "mscs:4:1",
    "python:2:5"
  ],
  "py-05-mutable-default": [
    "python:2:6",
    "python:8:2"
  ],
  "py-06-slicing": [
    "python:3:1",
    "python:3:2"
  ],
  "py-07-sets": [
    "python:3:4"
  ],
  "py-08-comprehensions": [
    "python:3:5",
    "python:3:6"
  ],
  "py-09-classes": [
    "cmpcbs:23:2",
    "python:5:1",
    "python:5:2",
    "python:5:5"
  ],
  "py-10-inheritance": [
    "python:5:3",
    "python:5:4"
  ],
  "py-11-generators": [
    "python:7:1",
    "python:7:2"
  ],
  "py-12-decorators": [
    "python:2:2",
    "python:7:3",
    "python:7:6"
  ],
  "py-13-typing": [
    "python:8:3"
  ],
  "py-14-stdlib-files": [
    "python:4:2",
    "python:6:5"
  ],
  "sql-01-join": [
    "clf-c02:3:13",
    "cmpcbs:7:5",
    "dea-c01:1:29",
    "dea-c01:3:7",
    "mscs:9:1"
  ],
  "sql-02-index": [
    "dea-c01:2:24",
    "mscs:9:4"
  ],
  "sql-03-normalise": [
    "mscs:9:3",
    "saa-c03:3:11"
  ],
  "sql-04-transaction": [
    "dea-c01:1:12",
    "mscs:9:5"
  ],
  "sql-05-view": [
    "dea-c01:3:12"
  ],
  "sql-06-plan": [
    "mscs:9:8"
  ]
};
