/**
 * Single source of truth for "what works", shown in Settings → About and
 * mirrored in STATUS.md. Keep honest: verified means covered by automated
 * tests run in CI; partial means implemented with known limits; unverified
 * means implemented but only manually checked; planned means not built.
 */
export type FeatureStatus = "verified" | "partial" | "unverified" | "planned";

export const FEATURE_STATUS: Array<{ feature: string; status: FeatureStatus; note: string }> = [
  { feature: "Terminal simulator", status: "verified", note: "49 documented commands, pipes, redirection, permissions, processes, services, simulated network table with listening sockets and connections, virtual sizes for large files. Unit-tested." },
  { feature: "Python execution (Pyodide)", status: "verified", note: "Real CPython 3.14 in a Web Worker with a 10s timeout. Execution core unit-tested in Node; browser worker checked end-to-end." },
  { feature: "Go lab (Yaegi interpreter in WebAssembly)", status: "verified", note: "Real Go incl. goroutines, channels, select, sync, generics and most of the standard library, in a Web Worker with a 10s timeout. Single-threaded WebAssembly: bare data races do not reproduce (see the race-detector service). Runtime built from go/runner in CI; Node + browser tests." },
  { feature: "Big O laboratory", status: "verified", note: "9 instrumented algorithms, step-through, growth tables, comparisons. Unit-tested." },
  { feature: "34 missions", status: "verified", note: "5 Linux, 5 Python, 5 Go, 3 Big O, 2 security, 4 CI/CD, 7 incidents (4 platform, 3 serverless), 2 design exercises, 1 lesson (Agile/Scrum). Each verified completable by automated tests; shortcut fixes (retry, skip, paste a secret, shed traffic) are rejected." },
  { feature: "Beginner primers", status: "verified", note: "Every mission opens with a plain-words primer (what it is, why it matters, why this way) and a 'why start here' note by the hints. Expanded for the unnamed-role track, collapsed for the SDE II track, switchable in Settings. Content rules unit-tested; browser scenario checks both levels." },
  { feature: "Role-specific interview questions", status: "verified", note: "9 technical questions per target role, each tied to one quoted qualification and to the missions that prepare for it, with practice 'listening for' cues. Selectable in Practice, used as the Realistic mode's technical follow-up, listed on the Curriculum role lens. Content rules unit-tested; browser scenario covers the flow." },
  { feature: "Redo after completion", status: "verified", note: "A completed mission or lesson reopens with a fresh workstation and hints on; the completion, reflections and retention history stay, dependants stay unlocked, and finishing again changes no mastery. 'Start over' still forgets the completion entirely. Unit + e2e tested." },
  { feature: "Study catalog (Ascendra snapshot, 20 courses)", status: "partial", note: "11 AWS certification and 9 core CS/security courses from the Ascendra project: 1,481 objectives with unit weights and gates, browsable under Study; 66 objectives link to the OpsForge mission that teaches them. Catalog build, ids, links and provenance unit-tested; browse e2e. Lessons, check questions, objective status and the planned labs are not built yet; unofficial, not a credential." },
  { feature: "Study objective status and mission bridge", status: "verified", note: "Ascendra's 0–4 rubric (Introduced, Guided, Independent, Transfer-ready, Needs review) resolved over attempt history, 1/7/21-day reviews, readiness weighted by exam domain; completing a mission credits its linked objectives once, to Guided. Own IndexedDB tables (schema 2; v1 exports still import). Unit + e2e tested. Lessons and check questions that would raise status past Guided are not built yet." },
  { feature: "Study lesson generation (local script)", status: "partial", note: "scripts/generate-study.mts writes lessons, question banks and unit scenarios as static JSON with structured outputs, resumable, validated before writing. Runs only with the owner's API key, never in CI; no lessons are committed until the owner generates and reviews SAA-C03." },
  { feature: "Study lesson loop", status: "verified", note: "Guess from intuition, read (beginner paragraph open on the unnamed-role track), one check question at a time (unseen first, choices reshuffled), explain it back against the model answer and rubric (self-rated, capped at Independent), summary. Misses schedule 1/7/21-day reviews that Today surfaces. Study style setting orders objectives by doing or reading first. Selection unit-tested; the loop e2e-tested against a fixture lesson since generated content is not committed yet." },
  { feature: "Study grading via the proxy, unit scenarios", status: "partial", note: "Explain-it-back answers and unit scenarios go to the local coaching proxy (POST /api/study/grade, graded against the model answer and rubric the request carries) when Claude coaching is on, consented and configured; proxy verdicts are what Transfer-ready needs. Otherwise the model answers are revealed and the learner self-rates, which caps at Independent. Fallbacks unit-tested; the proxy path is not exercised in CI (needs a key)." },
  { feature: "Authorization policy lab", status: "verified", note: "A vendor-neutral policy language on a fictional platform with the shared decision rules (default deny, explicit deny wins, boundary and organisation guardrail as ceilings, cross-account needs both sides, tag conditions) and a per-request decision trace; six exercises that credit 18 Study objectives. Engine and every exercise unit-tested; e2e passes an exercise from a Study objective." },
  { feature: "Persistent progress", status: "verified", note: "IndexedDB via Dexie; export/import/reset. Covered by tests and e2e reload check." },
  { feature: "Adaptive learning", status: "partial", note: "Mastery from demonstrated work, hint penalties, prerequisites, spaced-repetition due dates, retention checks (fresh replay without hints) and recommendations. Transfer-task variants are planned." },
  { feature: "STAR Academy + 16 Leadership Principles", status: "verified", note: "Official wording verified against amazon.jobs on 2026-10-09; three practice questions and an interview cue per principle. Content tests check all 16." },
  { feature: "Story Bank", status: "verified", note: "Create, edit, tag, export, import, delete. Local only." },
  { feature: "Rule-based STAR feedback and scoring", status: "verified", note: "Transparent rubric; cannot judge truth or technical correctness. Unit-tested." },
  { feature: "Dive Deeper Mode", status: "verified", note: "Gap detection, prioritised follow-ups, three depth levels, conversation state, honest stopping rules. Unit-tested." },
  { feature: "Mock interview modes", status: "partial", note: "Guided, Practice and Realistic (timed, multi-question) modes implemented; realistic mode technical follow-ups are drawn from a small pool." },
  { feature: "Voice: speech recognition + synthesis", status: "unverified", note: "Uses the browser's Web Speech API when available (Chrome/Edge best). Cannot be automated in CI; manual checks only. Text fallback always available." },
  { feature: "Delivery metrics (pace, fillers, pauses)", status: "partial", note: "Computed only from recognised transcript timing when a live recording occurred; never fabricated from text alone." },
  { feature: "Claude semantic coaching", status: "unverified", note: "Optional local proxy (server/) keeps the API key off the client. Falls back to rules when unreachable. Not exercised in CI (needs a key)." },
  { feature: "Monitoring dashboard", status: "verified", note: "Shared deterministic simulation engine (load, cache, database capacity, queue accumulation, read-replica lag and stale reads, optional serverless part: function concurrency, cold starts, poison messages, DLQ, retries); unit-tested; drives the incident missions." },
  { feature: "Incident management console", status: "verified", note: "Ticket, metrics, logs, architecture view, runbook actions, root cause, recovery verification, post-incident note. 7 scenarios proven solvable; symptom-only fixes rejected, including failing over to a lagging replica, adding consumers instead of a dead-letter queue, and turning retries off instead of making a handler idempotent." },
  { feature: "System architecture visualizer", status: "verified", note: "Live diagram with per-component health and traffic-weighted edges, in incidents and monitoring." },
  { feature: "CI/CD failure-mode missions", status: "verified", note: "Simulated pipeline runner and mission tools (ci, deployctl, metrics): flaky test, bad release rollback, broken secret wiring. Unit + e2e tested." },
  { feature: "Go missions (config parser, worker pool, timeouts/context, retries + idempotency, data race / double spend)", status: "verified", note: "Reference solutions proven in the WebAssembly runner; browser scenario completes a mission end to end. The double-spend race reproduces in the browser because its critical section blocks." },
  { feature: "Replication-lag scenario (read replica, stale reads, failover trap)", status: "verified", note: "Replica lag accumulates on the shared engine; the incident is solved by removing the blocking statement, pinning reads is a mitigation only, and failing over a lagging standby is rejected as data loss. Unit + e2e tested." },
  { feature: "Go race-detector service (optional, local)", status: "verified", note: "npm run race-server runs a program with go build -race on your machine and returns the detector report to the Go lab and Go missions. Unit tests run the real detector on the data-race mission (starter races, reference clean); the browser UI is e2e-tested in its unconfigured and unreachable states." },
  { feature: "Target roles and qualification gap map", status: "verified", note: "Two postings quoted as provided (the original qualifications and the SDE II Lambda/Serverless posting). Each qualification is mapped to skills with a coverage label; degree, tenure and clearance are marked not addressable; AWS products and Agile/Scrum are marked planned. Unit + e2e tested." },
  { feature: "Serverless track (simulated function platform)", status: "verified", note: "Concurrency limits and throttling (rate × duration), cold starts and provisioned concurrency, poison messages and dead-letter queues, at-least-once retries and idempotent handlers, on the shared simulation engine. Three incidents + one Python handler mission; unit + e2e tested. Generic concepts: not an emulation of AWS and no AWS experience is granted." },
  { feature: "Design-exercise mission type", status: "verified", note: "Requirements in, justified design out. Components with cost, capacity, latency and failure modes; the rubric computes cost, capacity, read latency, single points of failure and durability from the choices, checks sizing arithmetic, and asks failure drills whose correct answer depends on the design. The justification check is structural only and says so. Unit + e2e tested; one exercise so far." },
  { feature: "Lesson missions (process topics with a scenario quiz)", status: "verified", note: "Agile and Scrum for an operations engineer: the loop, roles, artifacts, operational work in a sprint, failure modes; six scenario questions with explanations; an interview cue and a matching practice question in the general pool. A lesson cannot grant experience and says so." },
  { feature: "Mobile layout, keyboard navigation", status: "partial", note: "Responsive layout and labelled controls; e2e smoke test at phone width. Full accessibility audit pending." },
];
